### ISSUE TITLE
Add function to calculate the growth status for adolescent.

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-health-modules#3]
Introduce new function to calculate the growth status for adolescent.
Function name: calculateGrowthStatusForAdolescent({individual, weight, height, asOnDate})
Expected return: ````{zScore: <Value>}````

data sheet [link](https://docs.google.com/spreadsheets/d/19jmI-3GBn7uM_EivUNMOJh6SPY0DTe-C/edit#gid=1360922768)

**Comment by mahalakshme** [comment]
@sachsk I had created this card for this purpose: https://github.com/avniproject/avni-client/issues/1395 Can you make sure all the ACs here are met?

**Comment by mahalakshme** [comment]
@sachsk also it is not wfa it is bmiForAge for adoloscents that we need to calculate. Had also shared the card with @pkundu last Friday
